#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$3

# Retrieve resource usage statistics from Kubernetes
kubectl $2 $RESOURCE_TYPE -n $1 | tail -n +2 | while read line
do

  # Extract CPU and memory usage from the output
 NAME=$(echo $line | awk '{print $1}')
 CPU=$(echo $line | awk '{print $3}')
 MEMORY=$(echo $line | awk '{print $5}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
printf '%s, %s, %s, %s' "$RESOURCE_TYPE" "$NAME" "$CPU" "$MEMORY"
done
    
